# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/parametros.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 481)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 841, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.presetsListWidget = QtWidgets.QListWidget(self.tab_5)
        self.presetsListWidget.setGeometry(QtCore.QRect(20, 60, 351, 231))
        self.presetsListWidget.setObjectName("presetsListWidget")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(420, 30, 111, 17))
        self.label_17.setObjectName("label_17")
        self.nombrePresetLineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.nombrePresetLineEdit.setGeometry(QtCore.QRect(420, 60, 201, 25))
        self.nombrePresetLineEdit.setObjectName("nombrePresetLineEdit")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(430, 120, 101, 17))
        self.label_16.setObjectName("label_16")
        self.descripcionLineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.descripcionLineEdit.setGeometry(QtCore.QRect(420, 150, 341, 101))
        self.descripcionLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.descripcionLineEdit.setObjectName("descripcionLineEdit")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(30, 30, 131, 17))
        self.label_18.setObjectName("label_18")
        self.loadDefaultsButton = QtWidgets.QPushButton(self.tab_5)
        self.loadDefaultsButton.setGeometry(QtCore.QRect(20, 330, 201, 25))
        self.loadDefaultsButton.setObjectName("loadDefaultsButton")
        self.confirmarPushButton = QtWidgets.QPushButton(self.tab_5)
        self.confirmarPushButton.setGeometry(QtCore.QRect(240, 330, 111, 25))
        self.confirmarPushButton.setObjectName("confirmarPushButton")
        self.eliminarPresetpushButton = QtWidgets.QPushButton(self.tab_5)
        self.eliminarPresetpushButton.setGeometry(QtCore.QRect(500, 330, 111, 25))
        self.eliminarPresetpushButton.setObjectName("eliminarPresetpushButton")
        self.nuevoPresetButton = QtWidgets.QPushButton(self.tab_5)
        self.nuevoPresetButton.setGeometry(QtCore.QRect(370, 330, 111, 25))
        self.nuevoPresetButton.setObjectName("nuevoPresetButton")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 50, 141, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 131, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 131, 17))
        self.label_3.setObjectName("label_3")
        self.velMaxSpinBox = QtWidgets.QSpinBox(self.tab)
        self.velMaxSpinBox.setGeometry(QtCore.QRect(190, 50, 48, 26))
        self.velMaxSpinBox.setObjectName("velMaxSpinBox")
        self.velLineSpinBox = QtWidgets.QSpinBox(self.tab)
        self.velLineSpinBox.setGeometry(QtCore.QRect(190, 90, 48, 26))
        self.velLineSpinBox.setObjectName("velLineSpinBox")
        self.velAnguSpinBox = QtWidgets.QSpinBox(self.tab)
        self.velAnguSpinBox.setGeometry(QtCore.QRect(190, 130, 48, 26))
        self.velAnguSpinBox.setObjectName("velAnguSpinBox")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(30, 240, 131, 17))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(30, 320, 131, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(30, 360, 131, 17))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(30, 280, 131, 17))
        self.label_22.setObjectName("label_22")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 91, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 67, 17))
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 240, 61, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 280, 61, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 360, 81, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(280, 240, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(280, 280, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(280, 320, 67, 17))
        self.label_10.setObjectName("label_10")
        self.velMaxSpinBox_2 = QtWidgets.QSpinBox(self.tab)
        self.velMaxSpinBox_2.setGeometry(QtCore.QRect(180, 320, 48, 26))
        self.velMaxSpinBox_2.setObjectName("velMaxSpinBox_2")
        self.label_51 = QtWidgets.QLabel(self.tab)
        self.label_51.setGeometry(QtCore.QRect(450, 120, 141, 17))
        self.label_51.setObjectName("label_51")
        self.comboBox_24 = QtWidgets.QComboBox(self.tab)
        self.comboBox_24.setGeometry(QtCore.QRect(680, 110, 91, 25))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.comboBox_24.addItem("")
        self.label_52 = QtWidgets.QLabel(self.tab)
        self.label_52.setGeometry(QtCore.QRect(450, 80, 141, 17))
        self.label_52.setObjectName("label_52")
        self.comboBox_25 = QtWidgets.QComboBox(self.tab)
        self.comboBox_25.setGeometry(QtCore.QRect(680, 70, 91, 25))
        self.comboBox_25.setObjectName("comboBox_25")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.comboBox_25.addItem("")
        self.label_53 = QtWidgets.QLabel(self.tab)
        self.label_53.setGeometry(QtCore.QRect(450, 160, 221, 17))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab)
        self.label_54.setGeometry(QtCore.QRect(450, 20, 161, 17))
        self.label_54.setObjectName("label_54")
        self.comboBox_26 = QtWidgets.QComboBox(self.tab)
        self.comboBox_26.setGeometry(QtCore.QRect(680, 150, 91, 25))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_17.setText(_translate("Form", "Nombre preset:"))
        self.label_16.setText(_translate("Form", "Descripcion:"))
        self.label_18.setText(_translate("Form", "Lista de presets:"))
        self.loadDefaultsButton.setText(_translate("Form", "Cargar valores por defecto"))
        self.confirmarPushButton.setText(_translate("Form", "Guardar preset"))
        self.eliminarPresetpushButton.setText(_translate("Form", "Eliminar preset"))
        self.nuevoPresetButton.setText(_translate("Form", "Nuevo preset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Gestor de presets"))
        self.label.setText(_translate("Form", "Velocidad maxima:"))
        self.label_2.setText(_translate("Form", "Velocidad Lineal:"))
        self.label_3.setText(_translate("Form", "Velocidad Angular:"))
        self.label_19.setText(_translate("Form", "Tasa de muestreo: "))
        self.label_20.setText(_translate("Form", "Resolucion:"))
        self.label_21.setText(_translate("Form", "Filtro de ruido:"))
        self.label_22.setText(_translate("Form", "Campo de vision:"))
        self.label_4.setText(_translate("Form", "Telemetria:"))
        self.label_5.setText(_translate("Form", "Captura:"))
        self.comboBox_2.setItemText(0, _translate("Form", "1"))
        self.comboBox_2.setItemText(1, _translate("Form", "5"))
        self.comboBox_2.setItemText(2, _translate("Form", "10"))
        self.comboBox_2.setItemText(3, _translate("Form", "15"))
        self.comboBox_2.setItemText(4, _translate("Form", "20"))
        self.comboBox_3.setItemText(0, _translate("Form", "90"))
        self.comboBox_3.setItemText(1, _translate("Form", "135"))
        self.comboBox_3.setItemText(2, _translate("Form", "180"))
        self.comboBox_5.setItemText(0, _translate("Form", "Angular "))
        self.comboBox_5.setItemText(1, _translate("Form", "Range "))
        self.comboBox_5.setItemText(2, _translate("Form", "Intensity"))
        self.comboBox_5.setItemText(3, _translate("Form", "Speckle"))
        self.comboBox_5.setItemText(4, _translate("Form", "Median"))
        self.label_8.setText(_translate("Form", "Hz"))
        self.label_9.setText(_translate("Form", "Grados"))
        self.label_10.setText(_translate("Form", "Grados"))
        self.label_51.setText(_translate("Form", "Reduccion de ruido:"))
        self.comboBox_24.setItemText(0, _translate("Form", "a"))
        self.comboBox_24.setItemText(1, _translate("Form", "b"))
        self.comboBox_24.setItemText(2, _translate("Form", "c"))
        self.label_52.setText(_translate("Form", "Metodo de filtrado: "))
        self.comboBox_25.setItemText(0, _translate("Form", "a"))
        self.comboBox_25.setItemText(1, _translate("Form", "b"))
        self.comboBox_25.setItemText(2, _translate("Form", "c"))
        self.label_53.setText(_translate("Form", "Compensacion de movimiento:"))
        self.label_54.setText(_translate("Form", "Pre-procesamiento:"))
        self.comboBox_26.setItemText(0, _translate("Form", "a"))
        self.comboBox_26.setItemText(1, _translate("Form", "b"))
        self.comboBox_26.setItemText(2, _translate("Form", "c"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Telemetria y Captura"))
