# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/parametros.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1330, 575)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 131, 17))
        self.label_18.setObjectName("label_18")
        self.presetsListWidget = QtWidgets.QListWidget(Form)
        self.presetsListWidget.setGeometry(QtCore.QRect(10, 40, 231, 411))
        self.presetsListWidget.setObjectName("presetsListWidget")
        self.loadDefaultsButton = QtWidgets.QPushButton(Form)
        self.loadDefaultsButton.setGeometry(QtCore.QRect(260, 350, 201, 25))
        self.loadDefaultsButton.setObjectName("loadDefaultsButton")
        self.confirmarPushButton = QtWidgets.QPushButton(Form)
        self.confirmarPushButton.setGeometry(QtCore.QRect(260, 270, 111, 25))
        self.confirmarPushButton.setObjectName("confirmarPushButton")
        self.nuevoPresetButton = QtWidgets.QPushButton(Form)
        self.nuevoPresetButton.setGeometry(QtCore.QRect(260, 230, 111, 25))
        self.nuevoPresetButton.setObjectName("nuevoPresetButton")
        self.eliminarPresetpushButton = QtWidgets.QPushButton(Form)
        self.eliminarPresetpushButton.setGeometry(QtCore.QRect(260, 310, 111, 25))
        self.eliminarPresetpushButton.setObjectName("eliminarPresetpushButton")
        self.nombrePresetLineEdit = QtWidgets.QLineEdit(Form)
        self.nombrePresetLineEdit.setGeometry(QtCore.QRect(260, 40, 201, 25))
        self.nombrePresetLineEdit.setObjectName("nombrePresetLineEdit")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(260, 10, 111, 17))
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(260, 80, 101, 17))
        self.label_16.setObjectName("label_16")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(950, 20, 251, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(200, 110, 41, 17))
        self.label_13.setObjectName("label_13")
        self.velLineSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.velLineSpinBox.setGeometry(QtCore.QRect(140, 70, 48, 26))
        self.velLineSpinBox.setMaximum(3)
        self.velLineSpinBox.setSingleStep(1)
        self.velLineSpinBox.setObjectName("velLineSpinBox")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(200, 30, 41, 17))
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 141, 17))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 131, 17))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 131, 17))
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(200, 70, 41, 17))
        self.label_12.setObjectName("label_12")
        self.velMaxSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.velMaxSpinBox.setGeometry(QtCore.QRect(140, 30, 48, 26))
        self.velMaxSpinBox.setMaximum(3)
        self.velMaxSpinBox.setSingleStep(1)
        self.velMaxSpinBox.setObjectName("velMaxSpinBox")
        self.velAnguSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.velAnguSpinBox.setGeometry(QtCore.QRect(140, 110, 48, 26))
        self.velAnguSpinBox.setMaximum(3)
        self.velAnguSpinBox.setSingleStep(1)
        self.velAnguSpinBox.setObjectName("velAnguSpinBox")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(950, 180, 321, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(230, 30, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(10, 70, 131, 17))
        self.label_22.setObjectName("label_22")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 150, 131, 17))
        self.label_21.setObjectName("label_21")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(230, 110, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(230, 70, 67, 17))
        self.label_9.setObjectName("label_9")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(140, 70, 61, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_6.setGeometry(QtCore.QRect(140, 110, 81, 25))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 110, 131, 17))
        self.label_20.setObjectName("label_20")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 30, 61, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_7.setGeometry(QtCore.QRect(140, 150, 81, 25))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(950, 400, 341, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_53 = QtWidgets.QLabel(self.groupBox_3)
        self.label_53.setGeometry(QtCore.QRect(10, 120, 221, 17))
        self.label_53.setObjectName("label_53")
        self.label_52 = QtWidgets.QLabel(self.groupBox_3)
        self.label_52.setGeometry(QtCore.QRect(10, 40, 141, 17))
        self.label_52.setObjectName("label_52")
        self.label_51 = QtWidgets.QLabel(self.groupBox_3)
        self.label_51.setGeometry(QtCore.QRect(10, 80, 141, 17))
        self.label_51.setObjectName("label_51")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_5.setGeometry(QtCore.QRect(240, 40, 81, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_9.setGeometry(QtCore.QRect(240, 120, 81, 25))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_8.setGeometry(QtCore.QRect(240, 85, 81, 20))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.descripcionTextEdit = QtWidgets.QTextEdit(Form)
        self.descripcionTextEdit.setGeometry(QtCore.QRect(260, 110, 201, 101))
        self.descripcionTextEdit.setObjectName("descripcionTextEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_18.setText(_translate("Form", "Lista de presets:"))
        self.loadDefaultsButton.setText(_translate("Form", "Cargar valores por defecto"))
        self.confirmarPushButton.setText(_translate("Form", "Guardar preset"))
        self.nuevoPresetButton.setText(_translate("Form", "Nuevo preset"))
        self.eliminarPresetpushButton.setText(_translate("Form", "Eliminar preset"))
        self.label_17.setText(_translate("Form", "Nombre preset:"))
        self.label_16.setText(_translate("Form", "Descripcion:"))
        self.groupBox.setTitle(_translate("Form", "Telemetria:"))
        self.label_13.setText(_translate("Form", "rad/s"))
        self.label_11.setText(_translate("Form", "m/s"))
        self.label_3.setText(_translate("Form", "Velocidad maxima:"))
        self.label_5.setText(_translate("Form", "Velocidad Angular:"))
        self.label_4.setText(_translate("Form", "Velocidad Lineal:"))
        self.label_12.setText(_translate("Form", "m/s"))
        self.groupBox_2.setTitle(_translate("Form", "Captura:"))
        self.label_8.setText(_translate("Form", "Hz"))
        self.label_22.setText(_translate("Form", "Campo de vision:"))
        self.label_19.setText(_translate("Form", "Tasa de muestreo: "))
        self.label_21.setText(_translate("Form", "Filtro de ruido:"))
        self.label_10.setText(_translate("Form", "Grados?"))
        self.label_9.setText(_translate("Form", "Grados"))
        self.comboBox_3.setItemText(0, _translate("Form", "90"))
        self.comboBox_3.setItemText(1, _translate("Form", "135"))
        self.comboBox_3.setItemText(2, _translate("Form", "180"))
        self.comboBox_6.setItemText(0, _translate("Form", "Alta"))
        self.comboBox_6.setItemText(1, _translate("Form", "Media"))
        self.comboBox_6.setItemText(2, _translate("Form", "Baja"))
        self.label_20.setText(_translate("Form", "Resolucion:"))
        self.comboBox_2.setItemText(0, _translate("Form", "1"))
        self.comboBox_2.setItemText(1, _translate("Form", "5"))
        self.comboBox_2.setItemText(2, _translate("Form", "10"))
        self.comboBox_2.setItemText(3, _translate("Form", "15"))
        self.comboBox_2.setItemText(4, _translate("Form", "20"))
        self.comboBox_7.setItemText(0, _translate("Form", "Alto"))
        self.comboBox_7.setItemText(1, _translate("Form", "Medio"))
        self.comboBox_7.setItemText(2, _translate("Form", "Bajo"))
        self.groupBox_3.setTitle(_translate("Form", "Pre-procesamiento:"))
        self.label_53.setText(_translate("Form", "Compensacion de movimiento:"))
        self.label_52.setText(_translate("Form", "Metodo de filtrado: "))
        self.label_51.setText(_translate("Form", "Reduccion de ruido:"))
        self.comboBox_5.setItemText(0, _translate("Form", "Angular "))
        self.comboBox_5.setItemText(1, _translate("Form", "Gauss"))
        self.comboBox_5.setItemText(2, _translate("Form", "Range "))
        self.comboBox_5.setItemText(3, _translate("Form", "Intensity"))
        self.comboBox_5.setItemText(4, _translate("Form", "Speckle"))
        self.comboBox_5.setItemText(5, _translate("Form", "Median"))
        self.comboBox_9.setItemText(0, _translate("Form", "Alta"))
        self.comboBox_9.setItemText(1, _translate("Form", "Media"))
        self.comboBox_9.setItemText(2, _translate("Form", "Baja"))
        self.comboBox_8.setItemText(0, _translate("Form", "Alto"))
        self.comboBox_8.setItemText(1, _translate("Form", "Medio"))
        self.comboBox_8.setItemText(2, _translate("Form", "Bajo"))
