# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/parametros.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1330, 575)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.presetsListWidget = QtWidgets.QListWidget(Form)
        self.presetsListWidget.setGeometry(QtCore.QRect(10, 40, 231, 461))
        self.presetsListWidget.setObjectName("presetsListWidget")
        self.loadDefaultsButton = QtWidgets.QPushButton(Form)
        self.loadDefaultsButton.setGeometry(QtCore.QRect(260, 290, 91, 31))
        self.loadDefaultsButton.setObjectName("loadDefaultsButton")
        self.confirmarPushButton = QtWidgets.QPushButton(Form)
        self.confirmarPushButton.setGeometry(QtCore.QRect(330, 230, 51, 51))
        self.confirmarPushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-save-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confirmarPushButton.setIcon(icon)
        self.confirmarPushButton.setIconSize(QtCore.QSize(32, 32))
        self.confirmarPushButton.setObjectName("confirmarPushButton")
        self.nuevoPresetButton = QtWidgets.QPushButton(Form)
        self.nuevoPresetButton.setGeometry(QtCore.QRect(260, 230, 51, 51))
        self.nuevoPresetButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-clean-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nuevoPresetButton.setIcon(icon1)
        self.nuevoPresetButton.setIconSize(QtCore.QSize(32, 32))
        self.nuevoPresetButton.setObjectName("nuevoPresetButton")
        self.eliminarPresetpushButton = QtWidgets.QPushButton(Form)
        self.eliminarPresetpushButton.setGeometry(QtCore.QRect(10, 510, 51, 51))
        self.eliminarPresetpushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-delete-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminarPresetpushButton.setIcon(icon2)
        self.eliminarPresetpushButton.setIconSize(QtCore.QSize(32, 32))
        self.eliminarPresetpushButton.setObjectName("eliminarPresetpushButton")
        self.nombrePresetLineEdit = QtWidgets.QLineEdit(Form)
        self.nombrePresetLineEdit.setGeometry(QtCore.QRect(260, 50, 201, 31))
        self.nombrePresetLineEdit.setObjectName("nombrePresetLineEdit")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(260, 20, 111, 17))
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(260, 90, 101, 17))
        self.label_16.setObjectName("label_16")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(520, 20, 281, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(210, 70, 41, 17))
        self.label_13.setObjectName("label_13")
        self.velLineSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.velLineSpinBox.setGeometry(QtCore.QRect(150, 30, 48, 26))
        self.velLineSpinBox.setMaximum(3)
        self.velLineSpinBox.setSingleStep(1)
        self.velLineSpinBox.setObjectName("velLineSpinBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 131, 17))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(210, 30, 41, 17))
        self.label_12.setObjectName("label_12")
        self.velAnguSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.velAnguSpinBox.setGeometry(QtCore.QRect(150, 70, 48, 26))
        self.velAnguSpinBox.setMaximum(3)
        self.velAnguSpinBox.setSingleStep(1)
        self.velAnguSpinBox.setObjectName("velAnguSpinBox")
        self.descripcionTextEdit = QtWidgets.QTextEdit(Form)
        self.descripcionTextEdit.setGeometry(QtCore.QRect(260, 120, 201, 101))
        self.descripcionTextEdit.setObjectName("descripcionTextEdit")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(520, 150, 281, 191))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(10, 60, 111, 17))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(10, 150, 111, 17))
        self.label_28.setObjectName("label_28")
        self.rangoMaxSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.rangoMaxSpinBox.setGeometry(QtCore.QRect(140, 60, 48, 26))
        self.rangoMaxSpinBox.setMinimum(2)
        self.rangoMaxSpinBox.setMaximum(10)
        self.rangoMaxSpinBox.setSingleStep(1)
        self.rangoMaxSpinBox.setProperty("value", 5)
        self.rangoMaxSpinBox.setObjectName("rangoMaxSpinBox")
        self.prefijoLineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.prefijoLineEdit.setGeometry(QtCore.QRect(140, 150, 113, 25))
        self.prefijoLineEdit.setObjectName("prefijoLineEdit")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(10, 30, 151, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(10, 90, 111, 17))
        self.label_30.setObjectName("label_30")
        self.rangoMinSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.rangoMinSpinBox.setGeometry(QtCore.QRect(140, 90, 48, 26))
        self.rangoMinSpinBox.setMinimum(0)
        self.rangoMinSpinBox.setMaximum(9)
        self.rangoMinSpinBox.setSingleStep(1)
        self.rangoMinSpinBox.setProperty("value", 1)
        self.rangoMinSpinBox.setObjectName("rangoMinSpinBox")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(200, 60, 41, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(200, 90, 41, 17))
        self.label_15.setObjectName("label_15")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(210, 120, 67, 17))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(10, 120, 131, 17))
        self.label_32.setObjectName("label_32")
        self.fovSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.fovSpinBox.setGeometry(QtCore.QRect(140, 120, 61, 26))
        self.fovSpinBox.setMinimum(0)
        self.fovSpinBox.setMaximum(270)
        self.fovSpinBox.setSingleStep(15)
        self.fovSpinBox.setProperty("value", 45)
        self.fovSpinBox.setObjectName("fovSpinBox")
        self.stepsSpinBox = QtWidgets.QSpinBox(self.groupBox_5)
        self.stepsSpinBox.setGeometry(QtCore.QRect(140, 30, 61, 26))
        self.stepsSpinBox.setMinimum(0)
        self.stepsSpinBox.setMaximum(270)
        self.stepsSpinBox.setSingleStep(15)
        self.stepsSpinBox.setProperty("value", 45)
        self.stepsSpinBox.setObjectName("stepsSpinBox")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(520, 360, 311, 191))
        self.groupBox_6.setObjectName("groupBox_6")
        self.devStdSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.devStdSpinBox.setGeometry(QtCore.QRect(100, 90, 48, 26))
        self.devStdSpinBox.setMinimum(2)
        self.devStdSpinBox.setMaximum(10)
        self.devStdSpinBox.setObjectName("devStdSpinBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(10, 60, 67, 17))
        self.label.setObjectName("label")
        self.vecinosSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.vecinosSpinBox.setGeometry(QtCore.QRect(100, 60, 48, 26))
        self.vecinosSpinBox.setMinimum(5)
        self.vecinosSpinBox.setSingleStep(5)
        self.vecinosSpinBox.setObjectName("vecinosSpinBox")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_10.setObjectName("label_10")
        self.voxelSizeSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.voxelSizeSpinBox.setGeometry(QtCore.QRect(100, 150, 69, 26))
        self.voxelSizeSpinBox.setDecimals(2)
        self.voxelSizeSpinBox.setMinimum(0.01)
        self.voxelSizeSpinBox.setSingleStep(0.01)
        self.voxelSizeSpinBox.setObjectName("voxelSizeSpinBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 81, 17))
        self.label_6.setObjectName("label_6")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(10, 120, 131, 17))
        self.label_21.setObjectName("label_21")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(290, 90, 31, 17))
        self.label_25.setObjectName("label_25")
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(170, 60, 61, 17))
        self.label_39.setObjectName("label_39")
        self.zMinSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.zMinSpinBox.setGeometry(QtCore.QRect(230, 90, 48, 26))
        self.zMinSpinBox.setMinimum(2)
        self.zMinSpinBox.setMaximum(10)
        self.zMinSpinBox.setSingleStep(1)
        self.zMinSpinBox.setProperty("value", 5)
        self.zMinSpinBox.setObjectName("zMinSpinBox")
        self.zMaxSpinBox = QtWidgets.QSpinBox(self.groupBox_6)
        self.zMaxSpinBox.setGeometry(QtCore.QRect(230, 60, 48, 26))
        self.zMaxSpinBox.setMinimum(2)
        self.zMaxSpinBox.setMaximum(10)
        self.zMaxSpinBox.setSingleStep(1)
        self.zMaxSpinBox.setProperty("value", 5)
        self.zMaxSpinBox.setObjectName("zMaxSpinBox")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(290, 60, 31, 17))
        self.label_23.setObjectName("label_23")
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(170, 90, 61, 17))
        self.label_40.setObjectName("label_40")
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(870, 20, 281, 391))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setGeometry(QtCore.QRect(10, 170, 131, 17))
        self.label_26.setObjectName("label_26")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 91, 17))
        self.label_7.setObjectName("label_7")
        self.iteracionesSpinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.iteracionesSpinBox.setGeometry(QtCore.QRect(100, 120, 61, 26))
        self.iteracionesSpinBox.setMinimum(100)
        self.iteracionesSpinBox.setMaximum(5000)
        self.iteracionesSpinBox.setSingleStep(100)
        self.iteracionesSpinBox.setObjectName("iteracionesSpinBox")
        self.numPlanosSpinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.numPlanosSpinBox.setGeometry(QtCore.QRect(100, 60, 48, 26))
        self.numPlanosSpinBox.setMinimum(1)
        self.numPlanosSpinBox.setMaximum(10)
        self.numPlanosSpinBox.setObjectName("numPlanosSpinBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.label_9.setObjectName("label_9")
        self.distanciaSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.distanciaSpinBox.setGeometry(QtCore.QRect(100, 90, 69, 26))
        self.distanciaSpinBox.setMinimum(0.01)
        self.distanciaSpinBox.setSingleStep(0.01)
        self.distanciaSpinBox.setObjectName("distanciaSpinBox")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(10, 250, 91, 17))
        self.label_22.setObjectName("label_22")
        self.normalRadSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.normalRadSpinBox.setGeometry(QtCore.QRect(130, 250, 69, 26))
        self.normalRadSpinBox.setDecimals(1)
        self.normalRadSpinBox.setMinimum(0.1)
        self.normalRadSpinBox.setSingleStep(0.1)
        self.normalRadSpinBox.setObjectName("normalRadSpinBox")
        self.voxelSizeAlineacionSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.voxelSizeAlineacionSpinBox.setGeometry(QtCore.QRect(130, 200, 69, 26))
        self.voxelSizeAlineacionSpinBox.setDecimals(2)
        self.voxelSizeAlineacionSpinBox.setMinimum(0.01)
        self.voxelSizeAlineacionSpinBox.setSingleStep(0.01)
        self.voxelSizeAlineacionSpinBox.setObjectName("voxelSizeAlineacionSpinBox")
        self.label_41 = QtWidgets.QLabel(self.groupBox_7)
        self.label_41.setGeometry(QtCore.QRect(10, 200, 81, 17))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_7)
        self.label_42.setGeometry(QtCore.QRect(10, 280, 121, 17))
        self.label_42.setObjectName("label_42")
        self.normalMaxNnSpinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.normalMaxNnSpinBox.setGeometry(QtCore.QRect(130, 280, 61, 26))
        self.normalMaxNnSpinBox.setMinimum(1)
        self.normalMaxNnSpinBox.setMaximum(20)
        self.normalMaxNnSpinBox.setSingleStep(1)
        self.normalMaxNnSpinBox.setProperty("value", 10)
        self.normalMaxNnSpinBox.setObjectName("normalMaxNnSpinBox")
        self.label_43 = QtWidgets.QLabel(self.groupBox_7)
        self.label_43.setGeometry(QtCore.QRect(10, 320, 91, 17))
        self.label_43.setObjectName("label_43")
        self.fpfhMaxNnSpinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.fpfhMaxNnSpinBox.setGeometry(QtCore.QRect(130, 350, 61, 26))
        self.fpfhMaxNnSpinBox.setMinimum(10)
        self.fpfhMaxNnSpinBox.setMaximum(200)
        self.fpfhMaxNnSpinBox.setSingleStep(10)
        self.fpfhMaxNnSpinBox.setProperty("value", 100)
        self.fpfhMaxNnSpinBox.setObjectName("fpfhMaxNnSpinBox")
        self.label_44 = QtWidgets.QLabel(self.groupBox_7)
        self.label_44.setGeometry(QtCore.QRect(10, 350, 121, 17))
        self.label_44.setObjectName("label_44")
        self.fpfhRadSpinBox = QtWidgets.QSpinBox(self.groupBox_7)
        self.fpfhRadSpinBox.setGeometry(QtCore.QRect(130, 320, 61, 26))
        self.fpfhRadSpinBox.setMinimum(1)
        self.fpfhRadSpinBox.setMaximum(20)
        self.fpfhRadSpinBox.setSingleStep(1)
        self.fpfhRadSpinBox.setProperty("value", 5)
        self.fpfhRadSpinBox.setObjectName("fpfhRadSpinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_18.setText(_translate("Form", "Lista de presets:"))
        self.loadDefaultsButton.setToolTip(_translate("Form", "Cargar valores por defecto"))
        self.loadDefaultsButton.setText(_translate("Form", "Default"))
        self.confirmarPushButton.setToolTip(_translate("Form", "Guardar preset"))
        self.nuevoPresetButton.setToolTip(_translate("Form", "Limpiar campos"))
        self.eliminarPresetpushButton.setToolTip(_translate("Form", "Borrar preset seleccionado"))
        self.label_17.setText(_translate("Form", "Nombre preset:"))
        self.label_16.setText(_translate("Form", "Descripción:"))
        self.groupBox.setTitle(_translate("Form", "Telemetria:"))
        self.label_13.setText(_translate("Form", "rad/s"))
        self.label_5.setText(_translate("Form", "Velocidad Angular:"))
        self.label_4.setText(_translate("Form", "Velocidad Lineal:"))
        self.label_12.setText(_translate("Form", "m/s"))
        self.groupBox_5.setTitle(_translate("Form", "Captura de Nubes"))
        self.label_27.setText(_translate("Form", "Rango max:"))
        self.label_28.setText(_translate("Form", "Prefijo:"))
        self.prefijoLineEdit.setText(_translate("Form", "nube"))
        self.label_29.setText(_translate("Form", "Num Steps:"))
        self.label_30.setText(_translate("Form", "Rango min:"))
        self.label_14.setText(_translate("Form", "m"))
        self.label_15.setText(_translate("Form", "m"))
        self.label_31.setText(_translate("Form", "Grados"))
        self.label_32.setText(_translate("Form", "Campo de vision:"))
        self.groupBox_6.setTitle(_translate("Form", "Preprocesamiento"))
        self.label_2.setText(_translate("Form", "Dev. std:"))
        self.label.setText(_translate("Form", "Vecinos:"))
        self.label_10.setText(_translate("Form", "Filtrado de ruido:"))
        self.label_6.setText(_translate("Form", "Voxel size:"))
        self.label_21.setText(_translate("Form", "Downsampling:"))
        self.label_25.setText(_translate("Form", "m"))
        self.label_39.setText(_translate("Form", "z_max"))
        self.label_23.setText(_translate("Form", "m"))
        self.label_40.setText(_translate("Form", "z_min"))
        self.groupBox_7.setTitle(_translate("Form", "Procesamiento"))
        self.label_24.setText(_translate("Form", "Segmentación:"))
        self.label_26.setText(_translate("Form", "Alineación:"))
        self.label_8.setText(_translate("Form", "# planos:"))
        self.label_7.setText(_translate("Form", "Iteraciones:"))
        self.label_9.setText(_translate("Form", "Distancia:"))
        self.label_22.setText(_translate("Form", "Normal Rad:"))
        self.label_41.setText(_translate("Form", "Voxel size:"))
        self.label_42.setText(_translate("Form", "Normal max nn:"))
        self.label_43.setText(_translate("Form", "fpfh rad:"))
        self.label_44.setText(_translate("Form", "fpfh max nn:"))
import iconos_rc
