# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/procesamiento.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 463)
        self.comboBox_9 = QtWidgets.QComboBox(Form)
        self.comboBox_9.setGeometry(QtCore.QRect(710, 80, 91, 25))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(Form)
        self.comboBox_10.setGeometry(QtCore.QRect(710, 160, 91, 25))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(570, 80, 101, 17))
        self.label_11.setObjectName("label_11")
        self.comboBox_14 = QtWidgets.QComboBox(Form)
        self.comboBox_14.setGeometry(QtCore.QRect(710, 240, 91, 25))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(570, 240, 131, 17))
        self.label_15.setObjectName("label_15")
        self.comboBox_12 = QtWidgets.QComboBox(Form)
        self.comboBox_12.setGeometry(QtCore.QRect(710, 200, 91, 25))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(570, 120, 67, 17))
        self.label_12.setObjectName("label_12")
        self.comboBox_11 = QtWidgets.QComboBox(Form)
        self.comboBox_11.setGeometry(QtCore.QRect(710, 120, 91, 25))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(570, 200, 101, 17))
        self.label_14.setObjectName("label_14")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(570, 160, 101, 17))
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(560, 40, 161, 17))
        self.label_7.setObjectName("label_7")
        self.nubesListWidget = QtWidgets.QListWidget(Form)
        self.nubesListWidget.setGeometry(QtCore.QRect(20, 20, 451, 381))
        self.nubesListWidget.setObjectName("nubesListWidget")
        self.subirNubePushButton = QtWidgets.QPushButton(Form)
        self.subirNubePushButton.setGeometry(QtCore.QRect(720, 380, 89, 25))
        self.subirNubePushButton.setObjectName("subirNubePushButton")
        self.nombreNubeLineEdit = QtWidgets.QLineEdit(Form)
        self.nombreNubeLineEdit.setGeometry(QtCore.QRect(700, 300, 113, 25))
        self.nombreNubeLineEdit.setObjectName("nombreNubeLineEdit")
        self.descripcionNubeLineEdit = QtWidgets.QLineEdit(Form)
        self.descripcionNubeLineEdit.setGeometry(QtCore.QRect(700, 340, 113, 25))
        self.descripcionNubeLineEdit.setObjectName("descripcionNubeLineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(570, 300, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(570, 340, 131, 17))
        self.label_2.setObjectName("label_2")
        self.verNubePushButton = QtWidgets.QPushButton(Form)
        self.verNubePushButton.setGeometry(QtCore.QRect(570, 390, 111, 25))
        self.verNubePushButton.setObjectName("verNubePushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_9.setItemText(0, _translate("Form", "a"))
        self.comboBox_9.setItemText(1, _translate("Form", "b"))
        self.comboBox_9.setItemText(2, _translate("Form", "c"))
        self.comboBox_10.setItemText(0, _translate("Form", "a"))
        self.comboBox_10.setItemText(1, _translate("Form", "b"))
        self.comboBox_10.setItemText(2, _translate("Form", "c"))
        self.label_11.setText(_translate("Form", "Descripcion:"))
        self.comboBox_14.setItemText(0, _translate("Form", "a"))
        self.comboBox_14.setItemText(1, _translate("Form", "b"))
        self.comboBox_14.setItemText(2, _translate("Form", "c"))
        self.label_15.setText(_translate("Form", "Correspondencia: "))
        self.comboBox_12.setItemText(0, _translate("Form", "a"))
        self.comboBox_12.setItemText(1, _translate("Form", "b"))
        self.comboBox_12.setItemText(2, _translate("Form", "c"))
        self.label_12.setText(_translate("Form", "Metodo:"))
        self.comboBox_11.setItemText(0, _translate("Form", "a"))
        self.comboBox_11.setItemText(1, _translate("Form", "b"))
        self.comboBox_11.setItemText(2, _translate("Form", "c"))
        self.label_14.setText(_translate("Form", "Iteraciones:"))
        self.label_13.setText(_translate("Form", "Tolerancia:"))
        self.label_7.setText(_translate("Form", "Procesamiento:"))
        self.subirNubePushButton.setText(_translate("Form", "Subir nube"))
        self.label.setText(_translate("Form", "Nombre nube:"))
        self.label_2.setText(_translate("Form", "Descripcion nube:"))
        self.verNubePushButton.setText(_translate("Form", "Visualizar nube"))
