# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/procesamiento.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1330, 575)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(280, 10, 161, 17))
        self.label_7.setObjectName("label_7")
        self.nubesListWidget = QtWidgets.QListWidget(Form)
        self.nubesListWidget.setGeometry(QtCore.QRect(10, 30, 251, 481))
        self.nubesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.nubesListWidget.setObjectName("nubesListWidget")
        self.procesarNubePushButton = QtWidgets.QPushButton(Form)
        self.procesarNubePushButton.setGeometry(QtCore.QRect(280, 300, 131, 25))
        self.procesarNubePushButton.setObjectName("procesarNubePushButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 131, 17))
        self.label_4.setObjectName("label_4")
        self.filtroRuidoCheckBox = QtWidgets.QCheckBox(Form)
        self.filtroRuidoCheckBox.setGeometry(QtCore.QRect(280, 50, 121, 23))
        self.filtroRuidoCheckBox.setObjectName("filtroRuidoCheckBox")
        self.downsamplingCheckBox = QtWidgets.QCheckBox(Form)
        self.downsamplingCheckBox.setGeometry(QtCore.QRect(280, 80, 131, 23))
        self.downsamplingCheckBox.setObjectName("downsamplingCheckBox")
        self.alineacionCheckBox = QtWidgets.QCheckBox(Form)
        self.alineacionCheckBox.setGeometry(QtCore.QRect(280, 210, 92, 23))
        self.alineacionCheckBox.setObjectName("alineacionCheckBox")
        self.segmentacionCheckBox = QtWidgets.QCheckBox(Form)
        self.segmentacionCheckBox.setGeometry(QtCore.QRect(280, 180, 121, 23))
        self.segmentacionCheckBox.setObjectName("segmentacionCheckBox")
        self.filtradoRuidoFrame = QtWidgets.QFrame(Form)
        self.filtradoRuidoFrame.setGeometry(QtCore.QRect(450, 50, 181, 71))
        self.filtradoRuidoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filtradoRuidoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filtradoRuidoFrame.setObjectName("filtradoRuidoFrame")
        self.vecinosSpinBox = QtWidgets.QSpinBox(self.filtradoRuidoFrame)
        self.vecinosSpinBox.setGeometry(QtCore.QRect(100, 10, 48, 26))
        self.vecinosSpinBox.setMinimum(5)
        self.vecinosSpinBox.setSingleStep(5)
        self.vecinosSpinBox.setObjectName("vecinosSpinBox")
        self.label_2 = QtWidgets.QLabel(self.filtradoRuidoFrame)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.filtradoRuidoFrame)
        self.label.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.label.setObjectName("label")
        self.devStdSpinBox = QtWidgets.QSpinBox(self.filtradoRuidoFrame)
        self.devStdSpinBox.setGeometry(QtCore.QRect(100, 40, 48, 26))
        self.devStdSpinBox.setMinimum(2)
        self.devStdSpinBox.setMaximum(10)
        self.devStdSpinBox.setObjectName("devStdSpinBox")
        self.downsamplingFrame = QtWidgets.QFrame(Form)
        self.downsamplingFrame.setGeometry(QtCore.QRect(450, 120, 181, 41))
        self.downsamplingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downsamplingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downsamplingFrame.setObjectName("downsamplingFrame")
        self.voxelSizeSpinBox = QtWidgets.QDoubleSpinBox(self.downsamplingFrame)
        self.voxelSizeSpinBox.setGeometry(QtCore.QRect(100, 10, 69, 26))
        self.voxelSizeSpinBox.setDecimals(2)
        self.voxelSizeSpinBox.setMinimum(0.01)
        self.voxelSizeSpinBox.setSingleStep(0.01)
        self.voxelSizeSpinBox.setObjectName("voxelSizeSpinBox")
        self.label_3 = QtWidgets.QLabel(self.downsamplingFrame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_3.setObjectName("label_3")
        self.actualizarListaPushButton = QtWidgets.QPushButton(Form)
        self.actualizarListaPushButton.setGeometry(QtCore.QRect(10, 530, 131, 25))
        self.actualizarListaPushButton.setObjectName("actualizarListaPushButton")
        self.segmentacionFrame = QtWidgets.QFrame(Form)
        self.segmentacionFrame.setGeometry(QtCore.QRect(450, 160, 181, 101))
        self.segmentacionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.segmentacionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.segmentacionFrame.setObjectName("segmentacionFrame")
        self.label_6 = QtWidgets.QLabel(self.segmentacionFrame)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 91, 17))
        self.label_6.setObjectName("label_6")
        self.iteracionesSpinBox = QtWidgets.QSpinBox(self.segmentacionFrame)
        self.iteracionesSpinBox.setGeometry(QtCore.QRect(100, 70, 61, 26))
        self.iteracionesSpinBox.setMinimum(100)
        self.iteracionesSpinBox.setMaximum(5000)
        self.iteracionesSpinBox.setSingleStep(100)
        self.iteracionesSpinBox.setObjectName("iteracionesSpinBox")
        self.label_8 = QtWidgets.QLabel(self.segmentacionFrame)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.label_8.setObjectName("label_8")
        self.distanciaSpinBox = QtWidgets.QDoubleSpinBox(self.segmentacionFrame)
        self.distanciaSpinBox.setGeometry(QtCore.QRect(100, 40, 69, 26))
        self.distanciaSpinBox.setMinimum(0.01)
        self.distanciaSpinBox.setSingleStep(0.01)
        self.distanciaSpinBox.setObjectName("distanciaSpinBox")
        self.label_5 = QtWidgets.QLabel(self.segmentacionFrame)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 71, 17))
        self.label_5.setObjectName("label_5")
        self.numPlanosSpinBox = QtWidgets.QSpinBox(self.segmentacionFrame)
        self.numPlanosSpinBox.setGeometry(QtCore.QRect(100, 10, 48, 26))
        self.numPlanosSpinBox.setMinimum(1)
        self.numPlanosSpinBox.setMaximum(4)
        self.numPlanosSpinBox.setObjectName("numPlanosSpinBox")
        self.guardarProcesadaPushButton = QtWidgets.QPushButton(Form)
        self.guardarProcesadaPushButton.setGeometry(QtCore.QRect(280, 340, 131, 25))
        self.guardarProcesadaPushButton.setObjectName("guardarProcesadaPushButton")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(280, 150, 161, 17))
        self.label_9.setObjectName("label_9")
        self.vistaProcesamientoWidget = QtWidgets.QWidget(Form)
        self.vistaProcesamientoWidget.setGeometry(QtCore.QRect(650, 10, 661, 561))
        self.vistaProcesamientoWidget.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.vistaProcesamientoWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vistaProcesamientoWidget.setObjectName("vistaProcesamientoWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Pre-procesamiento:"))
        self.procesarNubePushButton.setText(_translate("Form", "Procesar nube"))
        self.label_4.setText(_translate("Form", "Nubes disponibes:"))
        self.filtroRuidoCheckBox.setText(_translate("Form", "Filtro de ruido"))
        self.downsamplingCheckBox.setText(_translate("Form", "Downsampling"))
        self.alineacionCheckBox.setText(_translate("Form", "Alineación"))
        self.segmentacionCheckBox.setText(_translate("Form", "Segmentación"))
        self.label_2.setText(_translate("Form", "Dev. std:"))
        self.label.setText(_translate("Form", "Vecinos:"))
        self.label_3.setText(_translate("Form", "Voxel size:"))
        self.actualizarListaPushButton.setText(_translate("Form", "Actualizar lista"))
        self.label_6.setText(_translate("Form", "Iteraciones:"))
        self.label_8.setText(_translate("Form", "# planos:"))
        self.label_5.setText(_translate("Form", "Distancia:"))
        self.guardarProcesadaPushButton.setText(_translate("Form", "Guardar proce."))
        self.label_9.setText(_translate("Form", "Procesamiento:"))
