# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/telecomando.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 459)
        self.avanzarPushButton = QtWidgets.QPushButton(Form)
        self.avanzarPushButton.setGeometry(QtCore.QRect(120, 100, 71, 25))
        self.avanzarPushButton.setObjectName("avanzarPushButton")
        self.reversaPushButton = QtWidgets.QPushButton(Form)
        self.reversaPushButton.setGeometry(QtCore.QRect(120, 180, 71, 25))
        self.reversaPushButton.setObjectName("reversaPushButton")
        self.izquierdaPushButton = QtWidgets.QPushButton(Form)
        self.izquierdaPushButton.setGeometry(QtCore.QRect(28, 140, 81, 25))
        self.izquierdaPushButton.setObjectName("izquierdaPushButton")
        self.derechaPushButton = QtWidgets.QPushButton(Form)
        self.derechaPushButton.setGeometry(QtCore.QRect(200, 140, 81, 25))
        self.derechaPushButton.setObjectName("derechaPushButton")
        self.stopPushButton = QtWidgets.QPushButton(Form)
        self.stopPushButton.setGeometry(QtCore.QRect(120, 140, 71, 25))
        self.stopPushButton.setObjectName("stopPushButton")
        self.posicionLabel = QtWidgets.QLabel(Form)
        self.posicionLabel.setGeometry(QtCore.QRect(320, 70, 241, 17))
        self.posicionLabel.setObjectName("posicionLabel")
        self.velocidadLabel = QtWidgets.QLabel(Form)
        self.velocidadLabel.setGeometry(QtCore.QRect(320, 110, 381, 17))
        self.velocidadLabel.setObjectName("velocidadLabel")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(60, 230, 301, 201))
        self.groupBox.setObjectName("groupBox")
        self.capturarPushButton = QtWidgets.QPushButton(self.groupBox)
        self.capturarPushButton.setGeometry(QtCore.QRect(20, 40, 71, 25))
        self.capturarPushButton.setObjectName("capturarPushButton")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(20, 80, 111, 17))
        self.label_19.setObjectName("label_19")
        self.numCapturasSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.numCapturasSpinBox.setGeometry(QtCore.QRect(170, 70, 48, 26))
        self.numCapturasSpinBox.setMaximum(10)
        self.numCapturasSpinBox.setSingleStep(1)
        self.numCapturasSpinBox.setProperty("value", 3)
        self.numCapturasSpinBox.setObjectName("numCapturasSpinBox")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.label_22.setObjectName("label_22")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(20, 110, 111, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(20, 170, 111, 17))
        self.label_21.setObjectName("label_21")
        self.rangoSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.rangoSpinBox.setGeometry(QtCore.QRect(170, 130, 48, 26))
        self.rangoSpinBox.setMaximum(10)
        self.rangoSpinBox.setSingleStep(1)
        self.rangoSpinBox.setProperty("value", 5)
        self.rangoSpinBox.setObjectName("rangoSpinBox")
        self.prefijoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.prefijoLineEdit.setGeometry(QtCore.QRect(170, 160, 113, 25))
        self.prefijoLineEdit.setObjectName("prefijoLineEdit")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setGeometry(QtCore.QRect(170, 100, 51, 26))
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMaximum(10.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 0.5)
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.avanzarPushButton.setText(_translate("Form", "Avanzar"))
        self.reversaPushButton.setText(_translate("Form", "Reversa"))
        self.izquierdaPushButton.setText(_translate("Form", "Girar Izq."))
        self.derechaPushButton.setText(_translate("Form", "Girar Der."))
        self.stopPushButton.setText(_translate("Form", "Stop"))
        self.posicionLabel.setText(_translate("Form", "Posición:"))
        self.velocidadLabel.setText(_translate("Form", "Velocidad:"))
        self.groupBox.setTitle(_translate("Form", "Captura de Nubes"))
        self.capturarPushButton.setText(_translate("Form", "Capturar"))
        self.label_19.setText(_translate("Form", "Num Capturas"))
        self.label_22.setText(_translate("Form", "Rango"))
        self.label_20.setText(_translate("Form", "Intervalos"))
        self.label_21.setText(_translate("Form", "Prefijo"))
        self.prefijoLineEdit.setText(_translate("Form", "nube"))
