# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/telecomando.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1021, 459)
        self.avanzarPushButton = QtWidgets.QPushButton(Form)
        self.avanzarPushButton.setGeometry(QtCore.QRect(160, 120, 81, 31))
        self.avanzarPushButton.setObjectName("avanzarPushButton")
        self.reversaPushButton = QtWidgets.QPushButton(Form)
        self.reversaPushButton.setGeometry(QtCore.QRect(160, 200, 81, 31))
        self.reversaPushButton.setObjectName("reversaPushButton")
        self.izquierdaPushButton = QtWidgets.QPushButton(Form)
        self.izquierdaPushButton.setGeometry(QtCore.QRect(58, 160, 91, 31))
        self.izquierdaPushButton.setObjectName("izquierdaPushButton")
        self.derechaPushButton = QtWidgets.QPushButton(Form)
        self.derechaPushButton.setGeometry(QtCore.QRect(250, 160, 91, 31))
        self.derechaPushButton.setObjectName("derechaPushButton")
        self.stopPushButton = QtWidgets.QPushButton(Form)
        self.stopPushButton.setGeometry(QtCore.QRect(160, 160, 81, 31))
        self.stopPushButton.setObjectName("stopPushButton")
        self.posicionLabel = QtWidgets.QLabel(Form)
        self.posicionLabel.setGeometry(QtCore.QRect(140, 20, 221, 21))
        self.posicionLabel.setText("")
        self.posicionLabel.setObjectName("posicionLabel")
        self.velocidadLabel = QtWidgets.QLabel(Form)
        self.velocidadLabel.setGeometry(QtCore.QRect(140, 60, 221, 21))
        self.velocidadLabel.setText("")
        self.velocidadLabel.setObjectName("velocidadLabel")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(420, 120, 341, 241))
        self.groupBox.setObjectName("groupBox")
        self.capturarPushButton = QtWidgets.QPushButton(self.groupBox)
        self.capturarPushButton.setGeometry(QtCore.QRect(20, 40, 151, 31))
        self.capturarPushButton.setObjectName("capturarPushButton")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(20, 110, 111, 17))
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(20, 200, 111, 17))
        self.label_21.setObjectName("label_21")
        self.rangoMaxSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.rangoMaxSpinBox.setGeometry(QtCore.QRect(180, 110, 48, 26))
        self.rangoMaxSpinBox.setMinimum(2)
        self.rangoMaxSpinBox.setMaximum(10)
        self.rangoMaxSpinBox.setSingleStep(1)
        self.rangoMaxSpinBox.setProperty("value", 6)
        self.rangoMaxSpinBox.setObjectName("rangoMaxSpinBox")
        self.prefijoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.prefijoLineEdit.setGeometry(QtCore.QRect(180, 200, 113, 31))
        self.prefijoLineEdit.setObjectName("prefijoLineEdit")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(20, 80, 151, 17))
        self.label_26.setObjectName("label_26")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.label_24.setObjectName("label_24")
        self.rangoMinSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.rangoMinSpinBox.setGeometry(QtCore.QRect(180, 140, 48, 26))
        self.rangoMinSpinBox.setMinimum(0)
        self.rangoMinSpinBox.setMaximum(9)
        self.rangoMinSpinBox.setSingleStep(1)
        self.rangoMinSpinBox.setProperty("value", 0)
        self.rangoMinSpinBox.setObjectName("rangoMinSpinBox")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(240, 110, 41, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(240, 140, 41, 17))
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(250, 170, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(20, 170, 131, 17))
        self.label_23.setObjectName("label_23")
        self.fovSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.fovSpinBox.setGeometry(QtCore.QRect(180, 170, 61, 26))
        self.fovSpinBox.setMinimum(0)
        self.fovSpinBox.setMaximum(270)
        self.fovSpinBox.setSingleStep(15)
        self.fovSpinBox.setProperty("value", 45)
        self.fovSpinBox.setObjectName("fovSpinBox")
        self.stepsSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.stepsSpinBox.setGeometry(QtCore.QRect(180, 80, 61, 26))
        self.stepsSpinBox.setMinimum(0)
        self.stepsSpinBox.setMaximum(270)
        self.stepsSpinBox.setSingleStep(15)
        self.stepsSpinBox.setProperty("value", 60)
        self.stepsSpinBox.setObjectName("stepsSpinBox")
        self.logCapturaLabel = QtWidgets.QLabel(Form)
        self.logCapturaLabel.setGeometry(QtCore.QRect(460, 100, 491, 21))
        self.logCapturaLabel.setText("")
        self.logCapturaLabel.setObjectName("logCapturaLabel")
        self.posicionLabel_3 = QtWidgets.QLabel(Form)
        self.posicionLabel_3.setGeometry(QtCore.QRect(420, 30, 71, 21))
        self.posicionLabel_3.setObjectName("posicionLabel_3")
        self.posicionLabel_4 = QtWidgets.QLabel(Form)
        self.posicionLabel_4.setGeometry(QtCore.QRect(50, 20, 81, 21))
        self.posicionLabel_4.setObjectName("posicionLabel_4")
        self.velocidadLabel_2 = QtWidgets.QLabel(Form)
        self.velocidadLabel_2.setGeometry(QtCore.QRect(50, 60, 81, 21))
        self.velocidadLabel_2.setObjectName("velocidadLabel_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 260, 281, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(210, 70, 41, 17))
        self.label_13.setObjectName("label_13")
        self.velLineSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.velLineSpinBox.setGeometry(QtCore.QRect(150, 30, 48, 26))
        self.velLineSpinBox.setMaximum(3)
        self.velLineSpinBox.setSingleStep(1)
        self.velLineSpinBox.setProperty("value", 1)
        self.velLineSpinBox.setObjectName("velLineSpinBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 131, 17))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(210, 30, 41, 17))
        self.label_12.setObjectName("label_12")
        self.velAnguSpinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.velAnguSpinBox.setGeometry(QtCore.QRect(150, 70, 48, 26))
        self.velAnguSpinBox.setMaximum(3)
        self.velAnguSpinBox.setSingleStep(1)
        self.velAnguSpinBox.setProperty("value", 1)
        self.velAnguSpinBox.setObjectName("velAnguSpinBox")
        self.iniciarOdomPushButton = QtWidgets.QPushButton(Form)
        self.iniciarOdomPushButton.setGeometry(QtCore.QRect(780, 150, 191, 31))
        self.iniciarOdomPushButton.setObjectName("iniciarOdomPushButton")
        self.finalizarOdomPushButton = QtWidgets.QPushButton(Form)
        self.finalizarOdomPushButton.setGeometry(QtCore.QRect(780, 200, 191, 31))
        self.finalizarOdomPushButton.setObjectName("finalizarOdomPushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.avanzarPushButton.setText(_translate("Form", "Avanzar"))
        self.reversaPushButton.setText(_translate("Form", "Reversa"))
        self.izquierdaPushButton.setText(_translate("Form", "Girar Izq."))
        self.derechaPushButton.setText(_translate("Form", "Girar Der."))
        self.stopPushButton.setText(_translate("Form", "Stop"))
        self.groupBox.setTitle(_translate("Form", "Captura de Nubes"))
        self.capturarPushButton.setText(_translate("Form", "Capturar"))
        self.label_22.setText(_translate("Form", "Rango max"))
        self.label_21.setText(_translate("Form", "Prefijo"))
        self.prefijoLineEdit.setText(_translate("Form", "nube"))
        self.label_26.setText(_translate("Form", "Steps"))
        self.label_24.setText(_translate("Form", "Rango min"))
        self.label_10.setText(_translate("Form", "m"))
        self.label_11.setText(_translate("Form", "m"))
        self.label_9.setText(_translate("Form", "Grados"))
        self.label_23.setText(_translate("Form", "Campo de vision:"))
        self.posicionLabel_3.setText(_translate("Form", "Captura:"))
        self.posicionLabel_4.setText(_translate("Form", "Posición:"))
        self.velocidadLabel_2.setText(_translate("Form", "Velocidad:"))
        self.groupBox_2.setTitle(_translate("Form", "Telemetria:"))
        self.label_13.setText(_translate("Form", "rad/s"))
        self.label_5.setText(_translate("Form", "Velocidad Angular:"))
        self.label_4.setText(_translate("Form", "Velocidad Lineal:"))
        self.label_12.setText(_translate("Form", "m/s"))
        self.iniciarOdomPushButton.setText(_translate("Form", "Iniciar Odometria"))
        self.finalizarOdomPushButton.setText(_translate("Form", "Finalizar Odometria"))
