# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/telecomando.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 459)
        self.avanzarPushButton = QtWidgets.QPushButton(Form)
        self.avanzarPushButton.setGeometry(QtCore.QRect(130, 40, 81, 25))
        self.avanzarPushButton.setObjectName("avanzarPushButton")
        self.reversaPushButton = QtWidgets.QPushButton(Form)
        self.reversaPushButton.setGeometry(QtCore.QRect(130, 120, 81, 25))
        self.reversaPushButton.setObjectName("reversaPushButton")
        self.izquierdaPushButton = QtWidgets.QPushButton(Form)
        self.izquierdaPushButton.setGeometry(QtCore.QRect(28, 80, 91, 25))
        self.izquierdaPushButton.setObjectName("izquierdaPushButton")
        self.derechaPushButton = QtWidgets.QPushButton(Form)
        self.derechaPushButton.setGeometry(QtCore.QRect(210, 80, 91, 25))
        self.derechaPushButton.setObjectName("derechaPushButton")
        self.stopPushButton = QtWidgets.QPushButton(Form)
        self.stopPushButton.setGeometry(QtCore.QRect(130, 80, 71, 25))
        self.stopPushButton.setObjectName("stopPushButton")
        self.posicionLabel = QtWidgets.QLabel(Form)
        self.posicionLabel.setGeometry(QtCore.QRect(490, 70, 311, 17))
        self.posicionLabel.setText("")
        self.posicionLabel.setObjectName("posicionLabel")
        self.velocidadLabel = QtWidgets.QLabel(Form)
        self.velocidadLabel.setGeometry(QtCore.QRect(490, 110, 311, 17))
        self.velocidadLabel.setText("")
        self.velocidadLabel.setObjectName("velocidadLabel")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(40, 190, 341, 241))
        self.groupBox.setObjectName("groupBox")
        self.capturarPushButton = QtWidgets.QPushButton(self.groupBox)
        self.capturarPushButton.setGeometry(QtCore.QRect(20, 40, 151, 25))
        self.capturarPushButton.setObjectName("capturarPushButton")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(20, 110, 111, 17))
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(20, 200, 111, 17))
        self.label_21.setObjectName("label_21")
        self.rangoMaxSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.rangoMaxSpinBox.setGeometry(QtCore.QRect(180, 110, 48, 26))
        self.rangoMaxSpinBox.setMinimum(2)
        self.rangoMaxSpinBox.setMaximum(10)
        self.rangoMaxSpinBox.setSingleStep(1)
        self.rangoMaxSpinBox.setProperty("value", 5)
        self.rangoMaxSpinBox.setObjectName("rangoMaxSpinBox")
        self.prefijoLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.prefijoLineEdit.setGeometry(QtCore.QRect(180, 200, 113, 25))
        self.prefijoLineEdit.setObjectName("prefijoLineEdit")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(20, 80, 151, 17))
        self.label_26.setObjectName("label_26")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.label_24.setObjectName("label_24")
        self.rangoMinSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.rangoMinSpinBox.setGeometry(QtCore.QRect(180, 140, 48, 26))
        self.rangoMinSpinBox.setMinimum(0)
        self.rangoMinSpinBox.setMaximum(9)
        self.rangoMinSpinBox.setSingleStep(1)
        self.rangoMinSpinBox.setProperty("value", 1)
        self.rangoMinSpinBox.setObjectName("rangoMinSpinBox")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(240, 110, 41, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(240, 140, 41, 17))
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(250, 170, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(20, 170, 131, 17))
        self.label_23.setObjectName("label_23")
        self.fovSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.fovSpinBox.setGeometry(QtCore.QRect(180, 170, 61, 26))
        self.fovSpinBox.setMinimum(0)
        self.fovSpinBox.setMaximum(270)
        self.fovSpinBox.setSingleStep(15)
        self.fovSpinBox.setProperty("value", 45)
        self.fovSpinBox.setObjectName("fovSpinBox")
        self.stepsSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.stepsSpinBox.setGeometry(QtCore.QRect(180, 80, 61, 26))
        self.stepsSpinBox.setMinimum(0)
        self.stepsSpinBox.setMaximum(270)
        self.stepsSpinBox.setSingleStep(15)
        self.stepsSpinBox.setProperty("value", 45)
        self.stepsSpinBox.setObjectName("stepsSpinBox")
        self.logCapturaLabel = QtWidgets.QLabel(Form)
        self.logCapturaLabel.setGeometry(QtCore.QRect(490, 150, 311, 17))
        self.logCapturaLabel.setText("")
        self.logCapturaLabel.setObjectName("logCapturaLabel")
        self.posicionLabel_3 = QtWidgets.QLabel(Form)
        self.posicionLabel_3.setGeometry(QtCore.QRect(370, 150, 91, 17))
        self.posicionLabel_3.setObjectName("posicionLabel_3")
        self.posicionLabel_4 = QtWidgets.QLabel(Form)
        self.posicionLabel_4.setGeometry(QtCore.QRect(370, 70, 111, 17))
        self.posicionLabel_4.setObjectName("posicionLabel_4")
        self.velocidadLabel_2 = QtWidgets.QLabel(Form)
        self.velocidadLabel_2.setGeometry(QtCore.QRect(370, 110, 91, 17))
        self.velocidadLabel_2.setObjectName("velocidadLabel_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.avanzarPushButton.setText(_translate("Form", "Avanzar"))
        self.reversaPushButton.setText(_translate("Form", "Reversa"))
        self.izquierdaPushButton.setText(_translate("Form", "Girar Izq."))
        self.derechaPushButton.setText(_translate("Form", "Girar Der."))
        self.stopPushButton.setText(_translate("Form", "Stop"))
        self.groupBox.setTitle(_translate("Form", "Captura de Nubes"))
        self.capturarPushButton.setText(_translate("Form", "Capturar"))
        self.label_22.setText(_translate("Form", "Rango max"))
        self.label_21.setText(_translate("Form", "Prefijo"))
        self.prefijoLineEdit.setText(_translate("Form", "nube"))
        self.label_26.setText(_translate("Form", "Steps"))
        self.label_24.setText(_translate("Form", "Rango min"))
        self.label_10.setText(_translate("Form", "m"))
        self.label_11.setText(_translate("Form", "m"))
        self.label_9.setText(_translate("Form", "Grados"))
        self.label_23.setText(_translate("Form", "Campo de vision:"))
        self.posicionLabel_3.setText(_translate("Form", "Captura:"))
        self.posicionLabel_4.setText(_translate("Form", "Posición:"))
        self.velocidadLabel_2.setText(_translate("Form", "Velocidad:"))
