# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/user_registration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserRegistration(object):
    def setupUi(self, UserRegistration):
        UserRegistration.setObjectName("UserRegistration")
        UserRegistration.resize(1330, 575)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        UserRegistration.setFont(font)
        UserRegistration.setStyleSheet("")
        self.formulario_box = QtWidgets.QGroupBox(UserRegistration)
        self.formulario_box.setGeometry(QtCore.QRect(370, 20, 471, 531))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.formulario_box.setFont(font)
        self.formulario_box.setObjectName("formulario_box")
        self.label_10 = QtWidgets.QLabel(self.formulario_box)
        self.label_10.setGeometry(QtCore.QRect(260, 270, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.nameLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.nameLineEdit.setGeometry(QtCore.QRect(130, 50, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.emailLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.emailLineEdit.setGeometry(QtCore.QRect(130, 90, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setText("")
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.clearButton = QtWidgets.QPushButton(self.formulario_box)
        self.clearButton.setGeometry(QtCore.QRect(350, 470, 51, 51))
        self.clearButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-clean-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon)
        self.clearButton.setIconSize(QtCore.QSize(32, 32))
        self.clearButton.setObjectName("clearButton")
        self.IDLabel = QtWidgets.QLabel(self.formulario_box)
        self.IDLabel.setGeometry(QtCore.QRect(360, 270, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.IDLabel.setFont(font)
        self.IDLabel.setObjectName("IDLabel")
        self.label_4 = QtWidgets.QLabel(self.formulario_box)
        self.label_4.setGeometry(QtCore.QRect(30, 380, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.statusLabel = QtWidgets.QLabel(self.formulario_box)
        self.statusLabel.setGeometry(QtCore.QRect(30, 430, 421, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.label_2 = QtWidgets.QLabel(self.formulario_box)
        self.label_2.setGeometry(QtCore.QRect(30, 330, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.usernameLineEdit.setGeometry(QtCore.QRect(130, 280, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setText("")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.registerButton = QtWidgets.QPushButton(self.formulario_box)
        self.registerButton.setGeometry(QtCore.QRect(410, 470, 51, 51))
        self.registerButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-save-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.registerButton.setIcon(icon1)
        self.registerButton.setIconSize(QtCore.QSize(32, 32))
        self.registerButton.setObjectName("registerButton")
        self.label = QtWidgets.QLabel(self.formulario_box)
        self.label.setGeometry(QtCore.QRect(30, 280, 67, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.formulario_box)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 67, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.formulario_box)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.formulario_box)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.confirmLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.confirmLineEdit.setGeometry(QtCore.QRect(130, 380, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.confirmLineEdit.setFont(font)
        self.confirmLineEdit.setObjectName("confirmLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.passwordLineEdit.setGeometry(QtCore.QRect(130, 330, 113, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.groupBox = QtWidgets.QGroupBox(self.formulario_box)
        self.groupBox.setGeometry(QtCore.QRect(130, 110, 281, 71))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.adminRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.adminRadioButton.setGeometry(QtCore.QRect(10, 40, 121, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.adminRadioButton.setFont(font)
        self.adminRadioButton.setObjectName("adminRadioButton")
        self.operaRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.operaRadioButton.setGeometry(QtCore.QRect(150, 40, 112, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.operaRadioButton.setFont(font)
        self.operaRadioButton.setObjectName("operaRadioButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.formulario_box)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 170, 281, 71))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.activoRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.activoRadioButton.setGeometry(QtCore.QRect(10, 40, 112, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.activoRadioButton.setFont(font)
        self.activoRadioButton.setObjectName("activoRadioButton")
        self.inactivoRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.inactivoRadioButton.setGeometry(QtCore.QRect(150, 40, 112, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.inactivoRadioButton.setFont(font)
        self.inactivoRadioButton.setObjectName("inactivoRadioButton")
        self.label_7 = QtWidgets.QLabel(self.formulario_box)
        self.label_7.setGeometry(QtCore.QRect(30, 210, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.label_10.raise_()
        self.nameLineEdit.raise_()
        self.clearButton.raise_()
        self.IDLabel.raise_()
        self.label_4.raise_()
        self.statusLabel.raise_()
        self.label_2.raise_()
        self.usernameLineEdit.raise_()
        self.registerButton.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.confirmLineEdit.raise_()
        self.passwordLineEdit.raise_()
        self.label_7.raise_()
        self.emailLineEdit.raise_()
        self.lista_usuarios_box = QtWidgets.QGroupBox(UserRegistration)
        self.lista_usuarios_box.setGeometry(QtCore.QRect(10, 20, 351, 531))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lista_usuarios_box.setFont(font)
        self.lista_usuarios_box.setStyleSheet("")
        self.lista_usuarios_box.setFlat(False)
        self.lista_usuarios_box.setObjectName("lista_usuarios_box")
        self.tableWidget = QtWidgets.QTableWidget(self.lista_usuarios_box)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 331, 421))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.borrarButton = QtWidgets.QPushButton(self.lista_usuarios_box)
        self.borrarButton.setGeometry(QtCore.QRect(290, 470, 51, 51))
        self.borrarButton.setAutoFillBackground(False)
        self.borrarButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-delete-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.borrarButton.setIcon(icon2)
        self.borrarButton.setIconSize(QtCore.QSize(32, 32))
        self.borrarButton.setCheckable(False)
        self.borrarButton.setAutoDefault(False)
        self.borrarButton.setObjectName("borrarButton")
        self.editarButton = QtWidgets.QPushButton(self.lista_usuarios_box)
        self.editarButton.setGeometry(QtCore.QRect(232, 470, 51, 51))
        self.editarButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icons8-edit-pencil-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editarButton.setIcon(icon3)
        self.editarButton.setIconSize(QtCore.QSize(32, 32))
        self.editarButton.setObjectName("editarButton")

        self.retranslateUi(UserRegistration)
        QtCore.QMetaObject.connectSlotsByName(UserRegistration)

    def retranslateUi(self, UserRegistration):
        _translate = QtCore.QCoreApplication.translate
        UserRegistration.setWindowTitle(_translate("UserRegistration", "Form"))
        self.formulario_box.setTitle(_translate("UserRegistration", "Formulario "))
        self.label_10.setText(_translate("UserRegistration", "ID asignado:"))
        self.clearButton.setToolTip(_translate("UserRegistration", "Limpiar campos"))
        self.IDLabel.setText(_translate("UserRegistration", "No asignado"))
        self.label_4.setText(_translate("UserRegistration", "Contraseña:"))
        self.statusLabel.setText(_translate("UserRegistration", "Ingrese datos"))
        self.label_2.setText(_translate("UserRegistration", "Contraseña:"))
        self.registerButton.setToolTip(_translate("UserRegistration", "Guardar usuario"))
        self.label.setText(_translate("UserRegistration", "Usuario:"))
        self.label_3.setText(_translate("UserRegistration", "Nombre:"))
        self.label_6.setText(_translate("UserRegistration", "Correo:"))
        self.label_5.setText(_translate("UserRegistration", "Rol:"))
        self.adminRadioButton.setText(_translate("UserRegistration", "Administrador"))
        self.operaRadioButton.setText(_translate("UserRegistration", "Operario"))
        self.activoRadioButton.setText(_translate("UserRegistration", "Activo"))
        self.inactivoRadioButton.setText(_translate("UserRegistration", "Inactivo"))
        self.label_7.setText(_translate("UserRegistration", "Estado:"))
        self.lista_usuarios_box.setTitle(_translate("UserRegistration", "Lista de usuarios"))
        self.borrarButton.setToolTip(_translate("UserRegistration", "Borrar usuario seleccionado"))
        self.editarButton.setToolTip(_translate("UserRegistration", "Editar usuario seleccionado"))
import iconos_rc
import resources_rc
