# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/user_registration.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserRegistration(object):
    def setupUi(self, UserRegistration):
        UserRegistration.setObjectName("UserRegistration")
        UserRegistration.resize(849, 469)
        self.formulario_box = QtWidgets.QGroupBox(UserRegistration)
        self.formulario_box.setGeometry(QtCore.QRect(360, 20, 461, 371))
        self.formulario_box.setObjectName("formulario_box")
        self.label_10 = QtWidgets.QLabel(self.formulario_box)
        self.label_10.setGeometry(QtCore.QRect(260, 210, 91, 17))
        self.label_10.setObjectName("label_10")
        self.nameLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.nameLineEdit.setGeometry(QtCore.QRect(130, 40, 311, 25))
        self.nameLineEdit.setText("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.emailLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.emailLineEdit.setGeometry(QtCore.QRect(130, 80, 311, 25))
        self.emailLineEdit.setText("")
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.clearButton = QtWidgets.QPushButton(self.formulario_box)
        self.clearButton.setGeometry(QtCore.QRect(260, 290, 89, 25))
        self.clearButton.setObjectName("clearButton")
        self.IDLabel = QtWidgets.QLabel(self.formulario_box)
        self.IDLabel.setGeometry(QtCore.QRect(360, 210, 101, 17))
        self.IDLabel.setObjectName("IDLabel")
        self.label_4 = QtWidgets.QLabel(self.formulario_box)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 91, 17))
        self.label_4.setObjectName("label_4")
        self.statusLabel = QtWidgets.QLabel(self.formulario_box)
        self.statusLabel.setGeometry(QtCore.QRect(30, 340, 421, 17))
        self.statusLabel.setObjectName("statusLabel")
        self.label_2 = QtWidgets.QLabel(self.formulario_box)
        self.label_2.setGeometry(QtCore.QRect(30, 250, 91, 17))
        self.label_2.setObjectName("label_2")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.usernameLineEdit.setGeometry(QtCore.QRect(130, 210, 113, 25))
        self.usernameLineEdit.setText("")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.registerButton = QtWidgets.QPushButton(self.formulario_box)
        self.registerButton.setGeometry(QtCore.QRect(360, 290, 89, 25))
        self.registerButton.setObjectName("registerButton")
        self.label = QtWidgets.QLabel(self.formulario_box)
        self.label.setGeometry(QtCore.QRect(30, 210, 67, 17))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.formulario_box)
        self.label_3.setGeometry(QtCore.QRect(30, 40, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.formulario_box)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 91, 17))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.formulario_box)
        self.label_5.setGeometry(QtCore.QRect(30, 120, 91, 17))
        self.label_5.setObjectName("label_5")
        self.confirmLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.confirmLineEdit.setGeometry(QtCore.QRect(130, 290, 113, 25))
        self.confirmLineEdit.setObjectName("confirmLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.formulario_box)
        self.passwordLineEdit.setGeometry(QtCore.QRect(130, 250, 113, 25))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.groupBox = QtWidgets.QGroupBox(self.formulario_box)
        self.groupBox.setGeometry(QtCore.QRect(130, 90, 281, 61))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.adminRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.adminRadioButton.setGeometry(QtCore.QRect(10, 30, 121, 23))
        self.adminRadioButton.setObjectName("adminRadioButton")
        self.operaRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.operaRadioButton.setGeometry(QtCore.QRect(140, 30, 112, 23))
        self.operaRadioButton.setObjectName("operaRadioButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.formulario_box)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 140, 281, 61))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.activoRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.activoRadioButton.setGeometry(QtCore.QRect(10, 30, 112, 23))
        self.activoRadioButton.setObjectName("activoRadioButton")
        self.inactivoRadioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.inactivoRadioButton.setGeometry(QtCore.QRect(140, 30, 112, 23))
        self.inactivoRadioButton.setObjectName("inactivoRadioButton")
        self.label_7 = QtWidgets.QLabel(self.formulario_box)
        self.label_7.setGeometry(QtCore.QRect(30, 170, 91, 17))
        self.label_7.setObjectName("label_7")
        self.lista_usuarios_box = QtWidgets.QGroupBox(UserRegistration)
        self.lista_usuarios_box.setGeometry(QtCore.QRect(10, 20, 331, 371))
        self.lista_usuarios_box.setObjectName("lista_usuarios_box")
        self.tableWidget = QtWidgets.QTableWidget(self.lista_usuarios_box)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 311, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.borrarButton = QtWidgets.QPushButton(self.lista_usuarios_box)
        self.borrarButton.setGeometry(QtCore.QRect(220, 330, 89, 25))
        self.borrarButton.setObjectName("borrarButton")
        self.editarButton = QtWidgets.QPushButton(self.lista_usuarios_box)
        self.editarButton.setGeometry(QtCore.QRect(110, 330, 89, 25))
        self.editarButton.setObjectName("editarButton")

        self.retranslateUi(UserRegistration)
        QtCore.QMetaObject.connectSlotsByName(UserRegistration)

    def retranslateUi(self, UserRegistration):
        _translate = QtCore.QCoreApplication.translate
        UserRegistration.setWindowTitle(_translate("UserRegistration", "Form"))
        self.formulario_box.setTitle(_translate("UserRegistration", "Formulario "))
        self.label_10.setText(_translate("UserRegistration", "ID asignado:"))
        self.clearButton.setText(_translate("UserRegistration", "Limpiar"))
        self.IDLabel.setText(_translate("UserRegistration", "No asignado"))
        self.label_4.setText(_translate("UserRegistration", "Contraseña:"))
        self.statusLabel.setText(_translate("UserRegistration", "Ingrese datos"))
        self.label_2.setText(_translate("UserRegistration", "Contraseña:"))
        self.registerButton.setText(_translate("UserRegistration", "Registrar"))
        self.label.setText(_translate("UserRegistration", "Usuario:"))
        self.label_3.setText(_translate("UserRegistration", "Nombre:"))
        self.label_6.setText(_translate("UserRegistration", "Correo:"))
        self.label_5.setText(_translate("UserRegistration", "Rol:"))
        self.adminRadioButton.setText(_translate("UserRegistration", "Administrador"))
        self.operaRadioButton.setText(_translate("UserRegistration", "Operario"))
        self.activoRadioButton.setText(_translate("UserRegistration", "Activo"))
        self.inactivoRadioButton.setText(_translate("UserRegistration", "Inactivo"))
        self.label_7.setText(_translate("UserRegistration", "Estado:"))
        self.lista_usuarios_box.setTitle(_translate("UserRegistration", "Lista de usuarios"))
        self.borrarButton.setText(_translate("UserRegistration", "Borrar"))
        self.editarButton.setText(_translate("UserRegistration", "Editar"))
