# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/visualizacion.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1330, 552)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 131, 17))
        self.label_4.setObjectName("label_4")
        self.nubesListWidget = QtWidgets.QListWidget(Form)
        self.nubesListWidget.setGeometry(QtCore.QRect(10, 30, 251, 481))
        self.nubesListWidget.setObjectName("nubesListWidget")
        self.nombreNubeLineEdit = QtWidgets.QLineEdit(Form)
        self.nombreNubeLineEdit.setGeometry(QtCore.QRect(1200, 70, 113, 25))
        self.nombreNubeLineEdit.setObjectName("nombreNubeLineEdit")
        self.descripcionNubeLineEdit = QtWidgets.QLineEdit(Form)
        self.descripcionNubeLineEdit.setGeometry(QtCore.QRect(1200, 110, 113, 25))
        self.descripcionNubeLineEdit.setObjectName("descripcionNubeLineEdit")
        self.borrarNubePushButton = QtWidgets.QPushButton(Form)
        self.borrarNubePushButton.setGeometry(QtCore.QRect(160, 520, 101, 25))
        self.borrarNubePushButton.setObjectName("borrarNubePushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(1070, 30, 171, 17))
        self.label_3.setObjectName("label_3")
        self.subirNubePushButton = QtWidgets.QPushButton(Form)
        self.subirNubePushButton.setGeometry(QtCore.QRect(1220, 160, 89, 25))
        self.subirNubePushButton.setObjectName("subirNubePushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1070, 70, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1070, 110, 131, 17))
        self.label_2.setObjectName("label_2")
        self.verNubePushButton = QtWidgets.QPushButton(Form)
        self.verNubePushButton.setGeometry(QtCore.QRect(10, 520, 131, 25))
        self.verNubePushButton.setObjectName("verNubePushButton")
        self.generarReportePushButton = QtWidgets.QPushButton(Form)
        self.generarReportePushButton.setGeometry(QtCore.QRect(1070, 160, 131, 25))
        self.generarReportePushButton.setObjectName("generarReportePushButton")
        self.vtkWidget = QtWidgets.QWidget(Form)
        self.vtkWidget.setGeometry(QtCore.QRect(280, 30, 771, 531))
        self.vtkWidget.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.vtkWidget.setObjectName("vtkWidget")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1070, 270, 131, 17))
        self.label_5.setObjectName("label_5")
        self.descripcionNubeTextEdit = QtWidgets.QTextEdit(Form)
        self.descripcionNubeTextEdit.setGeometry(QtCore.QRect(1070, 300, 231, 111))
        self.descripcionNubeTextEdit.setObjectName("descripcionNubeTextEdit")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(1070, 420, 67, 17))
        self.label_6.setObjectName("label_6")
        self.fechaLineEdit = QtWidgets.QLineEdit(Form)
        self.fechaLineEdit.setGeometry(QtCore.QRect(1070, 450, 231, 25))
        self.fechaLineEdit.setObjectName("fechaLineEdit")
        self.vtkWidget.raise_()
        self.label_4.raise_()
        self.nubesListWidget.raise_()
        self.nombreNubeLineEdit.raise_()
        self.descripcionNubeLineEdit.raise_()
        self.borrarNubePushButton.raise_()
        self.label_3.raise_()
        self.subirNubePushButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.verNubePushButton.raise_()
        self.generarReportePushButton.raise_()
        self.label_5.raise_()
        self.descripcionNubeTextEdit.raise_()
        self.label_6.raise_()
        self.fechaLineEdit.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Nubes disponibes:"))
        self.borrarNubePushButton.setText(_translate("Form", "Borrar nube"))
        self.label_3.setText(_translate("Form", "Subir nubes de puntos:"))
        self.subirNubePushButton.setText(_translate("Form", "Subir nube"))
        self.label.setText(_translate("Form", "Nombre nube:"))
        self.label_2.setText(_translate("Form", "Descripcion nube:"))
        self.verNubePushButton.setText(_translate("Form", "Visualizar nube"))
        self.generarReportePushButton.setText(_translate("Form", "Exportar PDF"))
        self.label_5.setText(_translate("Form", "Descripcion nube:"))
        self.label_6.setText(_translate("Form", "Fecha:"))
